name: CI Pentesting

on:
  push:
    branches: [ main ]

jobs:
  build-push-sast:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1
      ECR_REPO: ciberv
      IMAGE_TAG: latest
      AWS_ACCOUNT_ID: 471112866011

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: AWS Login ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build & Push to ECR
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG .
          docker tag $ECR_REPO:$IMAGE_TAG \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

      - name: Trivy Scan
        run: |
          mkdir -p reports
          trivy image --format json -o reports/trivy-report.json $ECR_REPO:$IMAGE_TAG || true

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: reports/trivy-report.json

      - name: Fix PATH for Nuclei
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Nuclei Scan
        run: |
          mkdir -p reports
          nuclei -u http://localhost \
          -t /home/ubuntu/nuclei-templates/http/ \
          -json -o reports/nuclei-report.json || echo "Nuclei termin√≥ sin hallazgos"

      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: reports/nuclei-report.json

      - name: Deploy
        run: docker compose up -d

##Prueba jeje 
