name: CI Pentesting
on:
  push:
    branches: [ main ]
jobs:
  build-push-sast:
    runs-on: self-hosted
    env:
      AWS_REGION: us-east-1
      ECR_REPO: ciberv
      IMAGE_TAG: latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: AWS Login ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push to ECR
        run: |
          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
      - name: Trivy Scan
        run: |
          trivy image --format json -o trivy-report.json $ECR_REPO:$IMAGE_TAG || true
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
      - name: Nuclei Scan
        run: |
          nuclei -u http://localhost \
          -t /home/ubuntu/nuclei-templates/http/ \
          -json -o nuclei-report.json || true

      - name: Upload Nuclei Report
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei-report.json
      - name: Deploy
        run: docker compose up -d
