name: CI Pentesting
on:
  push:
    branches: [ main ]
jobs:
  build-push-sast:
    runs-on: self-hosted
    env:
      AWS_REGION: us-east-1
      ECR_REPO: wp-demo
      IMAGE_TAG: latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: AWS Login ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push to ECR
        run: |
          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
      - name: Trivy Scan
        run: trivy image --exit-code 1 --no-progress ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
      - name: Nuclei Scan
        run: nuclei -u http://localhost -t cves/ -stats
      - name: Deploy
        run: docker compose up -d
